apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    app: iib
  name: iib
spec:
  selector:
    matchLabels:
      app: iib # has to match .spec.template.metadata.labels
  serviceName: iib
  replicas: 2
  template:
    metadata:
      labels:
        app: iib
      name: iib
    spec:
      containers:
      - name: iib-mq
        env:
        - name: LICENSE
          value: accept
        - name: NODE_NAME
          value: IIB_NODE
        - name: SERVER_NAME
          value: IIB_SERVER
        - name: CACHE_POLICY
          value: "/tmp/globalcache-policy/globalcache_policy.xml"
        - name: CACHE_PORT_RANGE
          value: "2800-2819"
        - name: MQ_QMGR_NAME
          value: MQ1
        image: mycluster.icp:8500/default/iib-mq:10.0.0.11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2800
          name: globalcache0
        - containerPort: 2801
          name: globalcache1
        - containerPort: 2802
          name: globalcache2
        - containerPort: 2803
          name: globalcache3      
        - containerPort: 7800
          name: serverlistener
          protocol: TCP
        # - containerPort: 7080
        #   name: nodelistener
        #   protocol: TCP
        - containerPort: 4414
          name: webui
          protocol: TCP
        - containerPort: 1414
          name: mqlistener
          protocol: TCP
        - containerPort: 9443
          name: mqwebui
          protocol: TCP
#         readinessProbe:
#           failureThreshold: 3
#           httpGet:
#             path: /
#             port: 4414
#             scheme: HTTP
#           initialDelaySeconds: 15
#           periodSeconds: 10
#           successThreshold: 1
#           timeoutSeconds: 1

#         readinessProbe:
#           failureThreshold: 3
#           tcpSocket:
#             port: 7800
#           initialDelaySeconds: 15
#           periodSeconds: 10
#           successThreshold: 1
#           timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 4414
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/BARs
          name: bars
        - mountPath: /tmp/globalcache-policy
          name: globalcache-policy
      volumes:
      - name: globalcache-policy
        configMap:
          name: iib-globalcache-policy
      - name: bars
        persistentVolumeClaim:
          claimName: iib-pvc
