apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"labels":{"app":"calico"},"name":"configure-calico-mesh","namespace":"kube-system"},"spec":{"template":{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":""},"name":"configure-calico-mesh"},"spec":{"containers":[{"args":["config","set","nodeToNodeMesh","on"],"env":[{"name":"ETCD_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"etcd_endpoints","name":"calico-config"}}},{"name":"ETCD_CA_CERT_FILE","valueFrom":{"configMapKeyRef":{"key":"etcd_ca","name":"calico-config"}}},{"name":"ETCD_KEY_FILE","valueFrom":{"configMapKeyRef":{"key":"etcd_key","name":"calico-config"}}},{"name":"ETCD_CERT_FILE","valueFrom":{"configMapKeyRef":{"key":"etcd_cert","name":"calico-config"}}}],"image":"ibmcom/calico-ctl:v1.4.0","imagePullPolicy":"IfNotPresent","name":"configure-calico","volumeMounts":[{"mountPath":"/calico-secrets","name":"etcd-certs"}]}],"hostNetwork":true,"nodeSelector":{"beta.kubernetes.io/arch":"amd64","role":"master"},"restartPolicy":"OnFailure","tolerations":[{"effect":"NoSchedule","key":"dedicated","operator":"Equal","value":"master"},{"key":"CriticalAddonsOnly","operator":"Exists"}],"volumes":[{"name":"etcd-certs","secret":{"secretName":"calico-etcd-secrets"}}]}}}}
  creationTimestamp: 2018-02-16T16:11:08Z
  labels:
    app: calico
  name: configure-calico-mesh
  namespace: kube-system
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: ff81caf1-1333-11e8-a7b2-000c296ba764
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        controller-uid: ff81caf1-1333-11e8-a7b2-000c296ba764
        job-name: configure-calico-mesh
      name: configure-calico-mesh
    spec:
      containers:
      - args:
        - config
        - set
        - nodeToNodeMesh
        - "on"
        env:
        - name: ETCD_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: etcd_endpoints
              name: calico-config
        - name: ETCD_CA_CERT_FILE
          valueFrom:
            configMapKeyRef:
              key: etcd_ca
              name: calico-config
        - name: ETCD_KEY_FILE
          valueFrom:
            configMapKeyRef:
              key: etcd_key
              name: calico-config
        - name: ETCD_CERT_FILE
          valueFrom:
            configMapKeyRef:
              key: etcd_cert
              name: calico-config
        image: ibmcom/calico-ctl:v1.4.0
        imagePullPolicy: IfNotPresent
        name: configure-calico
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /calico-secrets
          name: etcd-certs
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        role: master
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: master
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - name: etcd-certs
        secret:
          defaultMode: 420
          secretName: calico-etcd-secrets
status:
  completionTime: 2018-02-16T16:11:25Z
  conditions:
  - lastProbeTime: 2018-02-16T16:11:25Z
    lastTransitionTime: 2018-02-16T16:11:25Z
    status: "True"
    type: Complete
  startTime: 2018-02-16T16:11:08Z
  succeeded: 1
