apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: iib-globalcache
  name: iib-globalcache
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: iib-globalcache
  serviceName: iib-globalcache
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: iib-globalcache
      name: iib-globalcache
    spec:
      containers:
      - env:
        - name: LICENSE
          value: accept
        - name: NODENAME
          value: IIB_NODE
        - name: SERVERNAME
          value: IIB_SERVER
        - name: CACHE_POLICY
          value: /tmp/globalcache-policy/policy_two_brokers_ha.xml
        - name: CACHE_PORT_RANGE
          value: 2800-2819
        image: mycluster.icp:8500/default/iibv10image:globalcache
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 4414
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: iib-globalcache
        ports:
        - containerPort: 2800
          name: globalcache0
          protocol: TCP
        - containerPort: 2801
          name: globalcache1
          protocol: TCP
        - containerPort: 2802
          name: globalcache2
          protocol: TCP
        - containerPort: 2803
          name: globalcache3
          protocol: TCP
        - containerPort: 7800
          name: serverlistener
          protocol: TCP
        - containerPort: 7080
          name: nodelistener
          protocol: TCP
        - containerPort: 4414
          name: webui
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/BARs
          name: bars
        - mountPath: /tmp/globalcache-policy
          name: globalcache-policy
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: iib-globalcache-policy
        name: globalcache-policy
      - name: bars
        persistentVolumeClaim:
          claimName: iib-pvc
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  replicas: 0
