kind: PersistentVolume
apiVersion: v1
metadata:
  name: iib-pv
  labels:
    type: local-storage
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/export/BARs"
    server: "mycluster.icp"
