apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-03-21T09:45:31Z
  generation: 36
  labels:
    app: ibm-integration-bus-prod
    chart: ibm-integration-bus-prod-exp-1.0.0
    heritage: Tiller
    release: ibm-integration-bus-prod-exp
  name: ibm-integration-bus-prod
  namespace: default
  resourceVersion: "4525737"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/ibm-integration-bus-prod
  uid: 98a90f9c-2cec-11e8-ab4c-000c296ba764
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibm-integration-bus-prod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ibm-integration-bus-prod
      name: ibm-integration-bus-prod
    spec:
      containers:
      - env:
        - name: LICENSE
          value: accept
        - name: NODENAME
          value: IIB_NODE
        - name: SERVERNAME
          value: IIB_SERVER
        image: mycluster.icp:8500/default/iib-prod:10.0.0.10
        imagePullPolicy: IfNotPresent
        name: ibm-integration-bus-prod
        ports:
        - containerPort: 7800
          name: serverlistener
          protocol: TCP
        - containerPort: 7080
          name: nodelistener
          protocol: TCP
        - containerPort: 4414
          name: webui
          protocol: TCP
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /
        #     port: 4414
        #     scheme: HTTP
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 7800
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 4414
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/BARs
          name: bars
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: bars
        persistentVolumeClaim:
          claimName: iib-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-03-21T09:45:32Z
    lastUpdateTime: 2018-03-21T09:45:32Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 36
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
