license: "accept"

image:
  # repository is the container repository to use, which must contain IBM MQ Advanced for Developers
  repository: mycluster.icp:8500/default/iib-mq 
  # tag is the tag to use for the container repository
  tag: 10.0.0.10
  # pullSecret is the secret to use when pulling the image from a private registry
  pullSecret:
  # pullPolicy is either IfNotPresent or Always (https://kubernetes.io/docs/concepts/containers/images/)
  pullPolicy: IfNotPresent

# persistence section specifies persistence settings which apply to the whole chart
persistence:
  # enabled is whether to use Persistent Volumes or not
  enabled: true
  # useDynamicProvisioning is whether or not to use Storage Classes to dynamically create Persistent Volumes
  useDynamicProvisioning: true

# dataPVC section specifies settings for the main Persistent Volume Claim, which is used for data in /var/mqm
dataPVC:
  # name sets part of the name for this Persistent Volume Claim
  name: "data"
  ## storageClassName is the name of the Storage Class to use, or an empty string for no Storage Class
  storageClassName: ""
  ## size is the minimum size of the Persistent Volume
  size: 2Gi

service:
  name: iib
  type: ClusterIP

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1
    memory: 512Mi

# queueManager section specifies settings for the MQ Queue Manager
queueManager:
  # name allows you to specify the name to use for the queue manager.  Defaults to the Helm release name.
  name: MQ1
  # dev section specifies settings for the MQ developer defaults available in the MQ Advanced for Developers image.
  dev:
    # adminPassword sets the password of the admin user
    adminPassword: passw0rd
    # appPassword sets the password of the app user
    appPassword: passw0rd
  enableswitchserver:
# iib section specifies settings for iib
iib:
  nodename: IIB_NODE
  servername: IIB_SERVER
  pvc: iib-pvc
  cache:
    policy: disabled
    portrange: 2800-2819
    configmap: iib-globalcache-policy
# nameOverride can be set to partially override the name of the resources created by this chart
nameOverride:
